# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Helios Code Block
email: ilpuccio.febo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Wrap all the progresses of my repos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://helios.github.com" # the base hostname & protocol for your site
twitter_username: ilpuccio
github_username:  helios

# Build settings
markdown: kramdown
